export enum ModulesCodes {
  SETTINGS = 'SETTINGS',
}

export enum SubModulesCodes {
  USER_MANAGEMENT = 'USER-MANAGEMENT',
  ROLES_AND_PERMISSION = 'ROLES-AND-PERMISSION',
  QUEUE_MANAGEMENT = 'QUEUE-MANAGEMENT',
  VENDORS_MANAGEMENT = 'VENDORS-MANAGEMENT',
  ACTIVITY_LOGS = 'ACTIVITY-LOGS',
}

export enum RolesMangementPermissions {
  CREATE = 'ROLES-PERMISSION-MANAGEMENT-CREATE',
  READ = 'ROLES-PERMISSION-MANAGEMENT-READ',
  UPDATE = 'ROLES-PERMISSION-MANAGEMENT-UPDATE',
  DELETE = 'ROLES-PERMISSION-MANAGEMENT-DELETE',
  MANAGE_PERMISSION = 'ROLES-PERMISSION-MANAGEMENT-MANAGE-PERMISSION',
}

export enum quizManagementPermissions {
  CREATE = 'QUIZ-MANAGEMENT-CREATE',
  READ = 'QUIZ-MANAGEMENT-READ',
  UPDATE = 'QUIZ-MANAGEMENT-UPDATE',
  DELETE = 'QUIZ-MANAGEMENT-DELETE',
  MANAGE_PERMISSION = 'QUIZ-MANAGEMENT-MANAGE-PERMISSION',
}
export enum vendorManagementPermissions {
  CREATE = 'VENDORS-MANAGEMENT-CREATE',
  READ = 'VENDORS-MANAGEMENT-READ',
  UPDATE = 'VENDORS-MANAGEMENT-UPDATE',
  DELETE = 'VENDORS-MANAGEMENT-DELETE',
  MANAGE_PERMISSION = 'VENDORS-MANAGEMENT-MANAGE-PERMISSION',
}
export enum offerManagementPermissions {
  CREATE = 'OFFERS-MANAGEMENT-CREATE',
  READ = 'OFFERS-MANAGEMENT-READ',
  UPDATE = 'OFFERS-MANAGEMENT-UPDATE',
  DELETE = 'OFFERS-MANAGEMENT-DELETE',
  MANAGE_PERMISSION = 'OFFERS-MANAGEMENT-MANAGE-PERMISSION',
}
export enum productManagementPermissions {
  CREATE = 'PRODUCTS-MANAGEMENT-CREATE',
  READ = 'PRODUCTS-MANAGEMENT-READ',
  UPDATE = 'PRODUCTS-MANAGEMENT-UPDATE',
  DELETE = 'PRODUCTS-MANAGEMENT-DELETE',
  MANAGE_PERMISSION = 'PRODUCTS-MANAGEMENT-MANAGE-PERMISSION',
}

export enum RolesCode {
  SUPER_ADMIN = 'SUPER-ADMIN',
  ADMIN = 'ADMIN',
  REPRESENTATIVE = 'REPRESENTATIVE',
}
