export enum ModulesCodes {
  SETTINGS = 'SETTINGS',
}

export enum SubModulesCodes {
  USER_MANAGEMENT = 'USER-MANAGEMENT',
  ROLES_AND_PERMISSION = 'ROLES-AND-PERMISSION',
  QUEUE_MANAGEMENT = 'QUEUE-MANAGEMENT',
  ACTIVITY_LOGS = 'ACTIVITY-LOGS',
}

export enum RolesMangementPermissions {
  CREATE = 'ROLES-PERMISSION-MANAGEMENT-CREATE',
  READ = 'ROLES-PERMISSION-MANAGEMENT-READ',
  UPDATE = 'ROLES-PERMISSION-MANAGEMENT-UPDATE',
  DELETE = 'ROLES-PERMISSION-MANAGEMENT-DELETE',
  MANAGE_PERMISSION = 'ROLES-PERMISSION-MANAGEMENT-MANAGE-PERMISSION',
}

export enum RolesCode {
  SUPER_ADMIN = 'SUPER-ADMIN',
  ADMIN = 'ADMIN',
  REPRESENTATIVE = 'REPRESENTATIVE',
}
