export enum UserMangementPermissions {
  CREATE = 'USER-MANAGEMENT-CREATE',
  READ = 'USER-MANAGEMENT-READ',
  UPDATE = 'USER-MANAGEMENT-UPDATE',
  DELETE = 'USER-MANAGEMENT-DELETE',
  INVITE = 'USER-MANAGEMENT-INVITE',
}
